server:
  port: 8080

spring:
  application:
    name: sk-ui-service

# For K8s/Harness: set these via env vars in Deployment
srikart:
  catalogBaseUrl: ${CATALOG_BASE_URL:http://localhost:8081}
  orderBaseUrl: ${ORDER_BASE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

